accepted = [
    "Apache-2.0",
    "MIT",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "CC0-1.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "OpenSSL",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "NOASSERTION",
    "Zlib",
    "GPL-3.0",
    "GPL-3.0 WITH Classpath-exception-2.0"
]
ignore-dev-dependencies = true
ignore-build-dependencies = true
workarounds = [
    "ring",
]
