[package]
name = "api-client-tutorial"
version = "0.1.0"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[dependencies]
substrate-api-client = { path = "../.." }
codec = { package = "parity-scale-codec", features = ["derive"], version = "2.0.0", default-features = false }

[dependencies.sp-core]
git = "https://github.com/paritytech/substrate.git"

[dependencies.keyring]
git = "https://github.com/paritytech/substrate.git"
package = "sp-keyring"
